name: Docker Build and Push
on:
  push:
    branches: [ main ] # Or any other branch you want to trigger on
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted

    # Required permissions for GitHub Actions to interact with Docker Hub
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.1-rootless # Use a specific version for better control

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io # Or docker.io for Docker Hub
          username: saeedhmohd244 # Or your Docker Hub username
          password: mishab@123 # Use a GitHub personal access token for GitHub Container Registry. For Docker Hub, use your Docker Hub password stored as a secret.

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # Path to your Dockerfile (usually the root of the repo)
          file: ./Dockerfile # Path to your Dockerfile (if it's not in the root)
          push: true
          tags: saeedhmohd244/devtinder-react:latest # Replace with your image name and tag.  For Docker Hub: your-dockerhub-username/your-repo-name:latest
          # For multi-architecture builds (optional):
          # platforms: linux/amd64,linux/arm64
          # build-args: |
          #   BUILD_VERSION=v1.2.3  # Example build argument

      - name: Image digest
        if: ${{ always() }}
        run: |
          echo "Image digest: ${{ steps.build-and-push.outputs.digest }}"